### Numpy
- a multidimentional array
#### Numpy vs Lists
Numpy is faster than lists because numpy uses **Fixed Type**.
- Numpy uses less bytes of memory which makes it quicker.
- Numpy uses contiguous Memory
#### Application
- Mathematics (MATLAP Replacement)
- Plotting (Matplotlib)
- Backend (Pands, Connect 4, Digital Photography)
- Machine Learning (Tensors)

### Load in Numpy

In [1]:
import numpy as np

#### The Basics


Initializing an array

In [3]:
# This a one dimentional array
a = np.array([1,2,3])
print(a)


[1 2 3]


In [4]:
# Two Dimentional Array
# Nesting list within an list
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


`array.ndmin` - to get the dimension of an array


In [6]:
a.ndim
b.ndim

2

`array.shape` - to get the rows and the columns

In [8]:
a.shape #(rows,) - since it's one dimentional
b.shape #(rows, columns)

(3,)

`array.dtype` - get the type of the array

In [10]:
a.dtype

dtype('int32')

Specifying data type in the array

In [13]:
c = np.array([1,2,3], dtype='int16')

`array.itemsize` - Returns the size of one array element in bytes.

In [11]:
a.itemsize # 4 byte since it is int32

4

In [18]:
b.itemsize # 8 bytes since it is in floats

8

In [14]:
c.itemsize # 2 bytes since it is int 16

2

`array.size` - Returns the total number of elements in the array.

In [15]:
c.size

3

To get the total size of the array in memory:

`array.size * array.itemsize`
or
`array.nbytes`

In [16]:
a.size * a.itemsize

12

In [17]:
a.nbytes

12