### Accessing/Changing Specific Elements, Rows, Columns, etc.

In [15]:
import numpy as np

In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
a.shape

(2, 7)

In [18]:
# Get a specific element [row, column]
# Remember we are zero-indexed
a[1, 5] # 2nd row, 6th column
a[1, -2] # 2nd row, second to the last column

13

In [19]:
# Get a specific row
a[0, :] #1st row, slice the column

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# Get a specific column
a[:, 2] #slice the row, 3rd column

array([ 3, 10])

In [21]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2] #1st Row, Get 2nd element to last element and step by 2 | even column

array([2, 4, 6])

Channging the Element

In [22]:
print(a)
a[1,5] = 20 #13 is changed to 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [25]:
# Changing all column values
a[:,2] = 5 #All 3rd column is now 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [26]:
# Changing column with different values by specifying the same shape as subsequence
a[:,2] = [1,2] #3rd column is 1 and 2
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3D Array Example

In [45]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
# Get specific element in 3D
# Tip: work outside in
b[0, 1, 1] #4

4

In [48]:
b[:,1,:]
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [38]:
# Replacing
b[:,1,:] = [[9,9], [8,8]]

#### Challenge

In [41]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [43]:
a[:, 2] = 20
print(a)

[[ 1  2 20  4  5]
 [ 6  7 20  9 10]]
