In [2]:
import numpy as np

### Initializing Different Types of Arrays

In [3]:
# All 0s matrix
np.zeros((2,3)) #Specify a shape of 2 x 3
np.zeros((2,3,5)) # 2 x 3 x 5 

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [4]:
# All 1s matrix
np.ones((4,2,2), dtype='int32') #4x2x2 with datatype of int32

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [5]:
# Any other number
#((shape), value)
np.full((2,2), 99) # 2x2 with values of 99 

array([[99, 99],
       [99, 99]])

In [6]:
# Any other number (full_like)
# Take a shape that's already been built
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.full_like(a, 4) # copies the 2x7 shape then all has value of 4
np.full(a.shape, 4) #this is same as above

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [12]:
# Random decimal numbers
np.random.rand(4,2) # random numbers between 0-1 of shape 4 x 2
np.random.random_sample(a.shape) #pass other shape
np.random.random_sample((2,5)) #pass a tuple

array([[0.91415827, 0.62022614, 0.19539346, 0.66662437, 0.89350368],
       [0.4768895 , 0.60373337, 0.84334896, 0.07466384, 0.34238494]])

In [29]:
# Random Integer values
np.random.randint(-4,8, size=(3,3)) #(start_value,end_value, shape)
np.random.randint(3, size=(3,3)) #end_value, shape

array([[1, 0, 0],
       [2, 1, 2],
       [1, 2, 2]])

In [33]:
# The identity matrix
np.identity(5) #square matrix, makes it 5x5, notice the 1's

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# Repeat an array
arr = np.array([[1,2,3], [4,5,6]]) # a 2 dimentional array
r1 = np.repeat(arr,3, axis=0) #array you want to repeat, will repeat the inner part
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


#### Challenge

In [35]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


#### Initialize Array Problem

In [49]:
# MY SOLUTION
output = np.ones((5,5))
output[1:-1,1:-1] = 0
output[2,2] = 9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [53]:
# RIGHT SOLUTION
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)

output[1:4,1:4] = z 
# or
output[1:-1,1:-1] = z

print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Challenge 2:
Output this:
```
[[0. 0. 0. 0. 0. 0. 0.]
[0. 1. 1. 1. 1. 1. 0.]
[0. 1. 1. 1. 1. 1. 0.]
[0. 1. 1. 5. 1. 1. 0.]
[0. 1. 1. 1. 1. 1. 0.]
[0. 1. 1. 1. 1. 1. 0.]
[0. 0. 0. 0. 0. 0. 0.]]
```

In [61]:
output = np.zeros((7,7))
print(output)
z = np.ones((5,5))
print(z)
z[2,2] = 5
print(z)

output[1:-1, 1:-1] = z
print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


##### Be careful when copying arrays!!!

In [ ]:
# THIS IS WRONG
a = np.array([1,2,3])
b = a #We set that variable b is pointing at the same thing as a
b[0] = 100

print(a)

In [ ]:
# Use the copy() function to copy the contents
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]
