In [2]:
import numpy as np

###### For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Mathematics

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


##### Perform operations to each element

In [6]:

a + 2

array([3, 4, 5, 6])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [7]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

##### Adding arrays to each other

In [11]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [12]:
a ** 2

array([ 9, 16, 25, 36])

In [13]:
# Take the sin
np.cos(a)



array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

##### Linear Algebra

In [16]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

# a*b won't work because they have different sizes
np.matmul(a,b) #matrix multiply
np.matmul(b,a) #matrix multiply

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

##### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc...

##### Statistics

`axis = 0` -> rows

`axis = 1` -> columns

In [29]:
stats = np.array([[1,2,3,8],[4,5,6,7]])
stats

array([[1, 2, 3, 8],
       [4, 5, 6, 7]])

In [34]:
np.min(stats)
np.min(stats, axis=1) #min of each column
np.min(stats, axis=0) #min in each row


array([1, 2, 3, 7])

In [38]:
np.max(stats) 
np.max(stats, axis=1) 
np.max(stats, axis=0)

array([8, 7])

In [43]:
np.sum(stats) # sum off all elements in the matrix
np.sum(stats, axis=1) # sum off each column
np.sum(stats, axis=0) # sum off each row

array([ 5,  7,  9, 15])

In [45]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()
b

15